let fs=require("fs")
fs.writeFileSync("./fs.txt","harsha")
fs.appendFileSync("./fs.txt","vardhan")
fs.appendFileSync("./fs.txt","  battu")
let file=fs.existsSync("./fss.txt")
fs.renameSync("./fs.js","./file.js")
let data=fs.readFileSync("./fs.txt","utf-8")
console.log(data)
console.log(file)
